const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'https://localhost:7208';
const API_TIMEOUT = 30000;
const HARDCODED_CREATED_BY_USER = 1;

export { API_BASE_URL, API_TIMEOUT, HARDCODED_CREATED_BY_USER };
